version: 2.1
jobs:
  shard-run-test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.47.0
    parallelism: 3
    steps:
      - checkout
      - run: npm ci
      - run: npx playwright install
      - run:
          name: Run tests
          command: SHARD="$((${CIRCLE_NODE_INDEX}+1))"; npx pwc --key $CURRENTS_RECORD_KEY --project-id 0biWxT --ci-build-id=shard-$CIRCLE_WORKFLOW_ID --reporter=junit --shard=${SHARD}/${CIRCLE_NODE_TOTAL}
      - store_test_results:
          path: results.xml

  or8n-run-test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.47.0
    parallelism: 3
    steps:
      - checkout
      - run: npm ci
      - run: npx playwright install
      - run:
          name: Run tests
          command: SHARD="$((${CIRCLE_NODE_INDEX}+1))"; npx pwc-p --key $CURRENTS_RECORD_KEY --project-id 0biWxT --reporter=junit --ci-build-id=or8n-$CIRCLE_WORKFLOW_ID
      - store_test_results:
          path: results.xml

# Invoke jobs via workflows
workflows:
  run-test-workflow:
    jobs:
      - shard-run-test:
          context: currents
      - or8n-run-test:
          context: currents
